pipeline {
    agent {
        node {
            label 'jenkins-slave-maven'
        }
    }
    environment {
        PATH = "/opt/apache-maven-3.9.6/bin:$PATH"
    }
    stages {
      stage("build"){
        steps {
            echo "----------- build started ----------"
            sh 'mvn clean deploy -Dfile="/home/ubuntu/jenkins/workspace/slave-test-build/ttrend-app"'
            echo "----------- build completed ----------"
        }
      }

    }
}